name: deploy web on github-page
on:
  push: main

jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd public
          git init
          git config --global user.email www.rafiulislam1998@gmail.com
          git config --global user.name MuhammadRafiulIslam9803
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/MuhammadRafiulIslam9803/doctors-portal-client.git